version: '3.8'

services:
  app:
    build: .
    volumes:
      - c:/rustdkr/steamcmd/rust:/steamcmd/rust
      - c:/rustdkr/usr/share/nginx/html:/usr/share/nginx/html
      - c:/rustdkr/var/log/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "28080:28080"
      - "28081:28081"
      - "28082:28082"
      - "28083:28083"
    env_file:
      - .env
