version: '3.8'

services:
  app:
    build: .
    volumes:
      - c:/rustdkr/steamcmd/rust:/steamcmd/rust
      - c:/rustdkr/usr/share/nginx/html:/usr/share/nginx/html
      - c:/rustdkr/var/log/nginx:/var/log/nginx
    ports:
      - "80:80/tcp"
      - "80:80/udp"
      - "28080:28080/tcp"
      - "28080:28080/udp"
      - "28081:28081/tcp"
      - "28081:28081/udp"
      - "28082:28082/tcp"
      - "28082:28082/udp"
      - "28083:28083/tcp"
      - "28083:28083/udp"
    env_file:
      - .env
